import type { ProgramListResponse } from "@apis/program/programList";

export const dummyProgramData: ProgramListResponse[] = [
  {
    programId: 1,
    programName: "건강체조 교실",
    category: "건강",
    date: "2025-11-15",
    dayOfWeek: "금",
    location: "정릉주간보호센터",
    startTime: "14:00",
    endTime: "15:30",
    currentApplicants: 15,
    capacity: 20,
    fee: "무료",
    thumbnail: "/img/dummy/ProgramDummyImage.png",
    bookmarked: true,
  },
  {
    programId: 2,
    programName: "실버요가 프로그램",
    category: "문화",
    date: "2025-11-18",
    dayOfWeek: "월",
    location: "성북노인복지관",
    startTime: "10:00",
    endTime: "11:30",
    currentApplicants: 18,
    capacity: 20,
    fee: "5,000원",
    thumbnail: "/img/dummy/ProgramDummyImage.png",
    bookmarked: false,
  },
  {
    programId: 3,
    programName: "인지능력 향상 프로그램",
    category: "치료",
    date: "2025-11-20",
    dayOfWeek: "수",
    location: "안암동 데이케어센터",
    startTime: "13:00",
    endTime: "14:30",
    currentApplicants: 12,
    capacity: 15,
    fee: "무료",
    thumbnail: "/img/dummy/ProgramDummyImage.png",
    bookmarked: false,
  },
];
